apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: thchinh26102000/udagram-api-feed
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-env
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap-env
                  key: POSTGRES_DB
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: configmap-env
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: configmap-env
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: configmap-env
                  key: AWS_PROFILE
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: configmap-env
                  key: JWT_SECRET
      restartPolicy: Always
