apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-feed
  name: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-feed
  template:
    metadata:
      labels:
        app: api-feed
    spec:
      containers:
      - name: api-feed
        image: 014091804/udagram-api-feed:latest
        ports:
          - containerPort: 8080
        imagePullPolicy: Always  
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: udagram-067328141418-env
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: udagram-067328141418-env
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: udagram-067328141418-env
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: udagram-067328141418-env
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: udagram-067328141418-env
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: udagram-067328141418-env
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: udagram-067328141418-env
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udagram-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: udagram-db-secret
              key: POSTGRES_USERNAME   
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"              
        volumeMounts:
        - name: aws-cre
          mountPath: "/root/.aws/"
          readOnly: true 
      restartPolicy: Always       
      volumes:
      - name: aws-cre
        secret:
          secretName: aws-cre      