apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  labels:
    run: reverse-proxy
spec:
  selector:
    run: reverse-proxy
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080